# Generated by Django 4.2.4 on 2023-10-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LATLONG', models.CharField(max_length=100)),
                ('TITLE', models.CharField(max_length=200)),
                ('TYPE', models.CharField(choices=[('restroom', 'Restroom'), ('parking', 'Parking Spot'), ('study', 'Study Spot')], max_length=10)),
                ('DESCRIPTION', models.TextField()),
            ],
        ),
    ]
