# Generated by Django 4.2.4 on 2023-10-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='APPROVED',
            field=models.BooleanField(default=False),
        ),
    ]
