# Generated by Django 4.2.4 on 2023-11-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_closetime_location_opentime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='CLOSETIME',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='OPENTIME',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
