# Generated by Django 4.2.4 on 2023-11-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_location_closetime_alter_location_opentime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='CLOSETIME',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='OPENTIME',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
